repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-docstring-first
